[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["echo 'Installing dependencies...'", "pip3 install --no-cache-dir -r requirements.txt || true"]

[phases.start]
cmd = "bash start.sh"

[start]
[[ports]]
port = "8000"
protocol = "http"
